src/model/Application.ts
=> Add DefaultApplicationTheme and make description optional

src/parser/ShogunApplicationUtil.spec.ts, src/parser/ShogunApplicationUtil.ts
This adds support for parsing WFS layers.
=> Add support for WFS layers in parser

src/model/File.ts, src/model/Group.ts, src/model/ImageFile.ts, src/model/User.ts, src/parser/ShogunApplicationUtil.spec.ts, src/service/AppInfoService/index.spec.ts, src/service/AppInfoService/index.ts, src/service/ApplicationService/index.spec.ts, src/service/AuthService/index.spec.ts, src/service/AuthService/index.ts, src/service/CacheService/index.spec.ts, src/service/CacheService/index.ts, src/service/FileService/index.spec.ts, src/service/FileService/index.ts, src/service/GenericFileService/index.spec.ts, src/service/GenericFileService/index.ts, src/service/GenericService/index.spec.ts, src/service/GenericService/index.ts, src/service/GraphQLService/index.spec.ts, src/service/GraphQLService/index.ts, src/service/GroupService/index.spec.ts, src/service/GroupService/index.ts, src/service/ImageFileService/index.spec.ts, src/service/ImageFileService/index.ts, src/service/LayerService/index.spec.ts, src/service/SHOGunClient.spec.ts, src/service/SHOGunClient.ts, src/service/UserService/index.spec.ts, src/service/UserService/index.ts, src/spec/fetchSpy.ts
This adds the missing models and services for the `Group`, `File`, `ImageFile` entities and updates the `User` model to match the current one in SHOGun as well.
Additionally some tests were updated, fixed and harmonized.
=> Add missing services

src/service/GenericFileService/index.spec.ts, src/service/GenericFileService/index.ts, src/service/GenericService/index.spec.ts, src/service/GenericService/index.ts
Delete operations do not return any content.
Please note @terrestris/devs.
=> Fix delete service methods

src/parser/SHOGunApplicationUtil.ts
=> Set correct scope

src/model/Group.ts, src/model/enum/PermissionCollectionType.ts, src/model/enum/PermissionType.ts, src/model/security/ClassPermission.ts, src/model/security/GroupClassPermission.ts, src/model/security/GroupInstancePermission.ts, src/model/security/InstancePermission.ts, src/model/security/PermissionCollection.ts, src/model/security/UserClassPermission.ts, src/model/security/UserInstancePermission.ts, src/service/GenericService/index.ts, src/service/PermissionService/index.spec.ts, src/service/PermissionService/index.ts
This initializes the `PermissionService` that includes all permission endpoints introduced in [PR54](https://github.com/terrestris/shogun/pull/54).
=> Add `PermissionService`

package-lock.json, package.json, src/parser/SHOGunApplicationUtil.spec.ts, src/parser/SHOGunApplicationUtil.ts, src/security/getBearerTokenHeader.ts, src/service/PermissionService/index.spec.ts
* Upgrade to ol v7.x and ol-util v10.x
* Also bump all other package dependencies
=> Upgrade dependencies

src/parser/SHOGunApplicationUtil.ts
This adds support for creating a `WMSTime` layer. 
It basically creates a `TileWMS` layer and appends the time dimension informations provided by the capabilities for further (optional) usage to it.
=> Add support for layer type WMSTime

src/parser/SHOGunApplicationUtil.ts
Solves CORS errors with various broken background services.
=> fix: use no-cors mode when requesting images

src/parser/SHOGunApplicationUtil.ts
Reverts the second 'fix' of #220 
=> fix: revert no-cors flag

src/model/Application.ts
This PR adds support to process legal information configuration from the `clientConfig`
=> Support legal information link config

src/parser/SHOGunApplicationUtil.ts
Only fetch layers with a set layer id.
=> fix: only fetch layers with layerId

src/model/Layer.ts, src/model/enum/EditFormComponentType.ts, src/parser/SHOGunApplicationUtil.spec.ts, src/parser/SHOGunApplicationUtil.ts, src/service/GenericService/index.spec.ts, src/service/GenericService/index.ts, src/service/SHOGunAPIClient.spec.ts
This PR provides the tools to read the information provided the layer whether it should be editable in general and also provides the processing of the form configuration for editing features on a layer.
=> Layer editable

.gitignore, src/graphqlqueries/Applications.ts
=> feat: introduce graphQL query to find application by id

README.md, package-lock.json, package.json, watchBuild.js
Introduce a script injecting a new build version of `shogun-util` to a referencing library (e.g. [shogun-gis-client](https://github.com/terrestris/shogun-gis-client/)) on source code changes.
Credits go to @LukasLohoff and  @simonseyock 
=> chore: introduce watch build script

src/parser/SHOGunApplicationUtil.ts
=> fix: pass keep client config param recursively

src/service/GenericEntityService/index.ts
=> feat: add find all no paging function

src/parser/SHOGunApplicationUtil.ts, src/service/GenericEntityService/index.ts, watchBuild.js
Herewith, the layer groups visibility is determine using the contained layers as well.
=> AppContect parser: Fix initial visibility of LayerGroup

src/model/Application.ts
See: https://github.com/terrestris/shogun-util/pull/659
=> Add faviconPath to DefaultApplicationTheme

src/service/GenericEntityService/index.spec.ts, src/service/GenericEntityService/index.ts
Compare https://github.com/terrestris/shogun-util/pull/661
=> Add methods for `PublicInstancePermission` to ol7 branch

src/model/Group.ts, src/model/Role.ts, src/model/security/RoleClassPermission.ts, src/model/security/RoleInstancePermission.ts, src/service/PermissionService/index.ts, src/service/RoleService/index.spec.ts, src/service/RoleService/index.ts, src/service/SHOGunAPIClient.spec.ts, src/service/SHOGunAPIClient.ts
This adds the client handling for the newly added models and interfaces in [#872](https://github.com/terrestris/shogun/pull/872).
=> Init `Role`, `RoleClassPermission` and `RoleInstancePermission` models

package-lock.json, src/model/Application.ts
This MR add the printApp to the interface for type assistance
=> feat: add print app

src/model/Layer.ts, src/parser/SHOGunApplicationUtil.spec.ts
This MR adds an additional placeholder property.
=> feat: adds an additional propertyConfig

src/model/Layer.ts, src/parser/SHOGunApplicationUtil.spec.ts
=> fix: remove unneeded property

src/parser/SHOGunApplicationUtil.ts
This sets the required erroneous tile state to an `ImageTile` if no valid image could be loaded. Without an erroneous tile is blocking other requests.
In addition the behaviour of revoking the object url is optimized/simplified.
=> Correctly set the tile state on error

package-lock.json, package.json, watchBuild.js
This fixes three highly ranked vulnerabilities.
=> Replace `watch` with `chokidar` in `watch:buildto` script

src/graphqlqueries/Layers.ts
=> feat: introduce allLayers graphql query

src/service/GroupService/index.spec.ts, src/service/GroupService/index.ts, src/service/RoleService/index.spec.ts, src/service/RoleService/index.ts, src/service/UserService/index.spec.ts, src/service/UserService/index.ts
This adds the endpoints introduced in [#947](https://github.com/terrestris/shogun/pull/947) to the util.
=> Add service methods to create users, groups and roles from the provider

src/service/ApplicationService/index.spec.ts, src/service/ApplicationService/index.ts
According to the new [SHOGun-API endpoint](https://github.com/terrestris/shogun/pull/966), this util introduces a new fetch function.
=> feat: extends the util by a find by name function

src/parser/SHOGunApplicationUtil.ts
=> fix: set extent from parsed tilegrid

src/model/enum/LayerType.ts, src/parser/SHOGunApplicationUtil.spec.ts, src/parser/SHOGunApplicationUtil.ts
=> feat: add support for Mapbox Vector Tile layers

src/model/Layer.ts, src/parser/SHOGunApplicationUtil.ts
Related to [PR 1051](https://github.com/terrestris/shogun/pull/1051).
=> Add field `styleUrl` to layer
