terrestris/shogun-util

- src/graphqlqueries/Layers.ts
- src/parser/SHOGunApplicationUtil.spec.ts
- src/parser/SHOGunApplicationUtil.ts
- src/service/GraphQLService/index.spec.ts
- src/service/GraphQLService/index.ts
* Fetch all configured application layers at once via `allLayersByIds` query
* Add some tests and null checks
Introduces breaking change due to modification of `parseNodes` and `parseFolder` method arguments.
Both methods are expecting a mandatory array of layer entities as second argument.
Old signature:
```
parseNodes(nodes: DefaultLayerTree[], projection?: OlProjectionLike)
parseFolder(nodes: DefaultLayerTree[], projection?: OlProjectionLike)
```
New signature: 
```
parseNodes(nodes: DefaultLayerTree[], layers: Layer[], projection?: OlProjectionLike)
parseFolder(nodes: DefaultLayerTree[], layers: Layer[], projection?: OlProjectionLike)
```
> Bundle layer request

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
Allows to control the layer parameter `TRANSPARENT` via the layer `sourceConfig`. By default the value remains `true`.
> Configurable transparent parameter

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
Provides the processing of the `sourceConfig` parameter `requestParams` (for TRANSPAREN and other params in perspective) . The [previously](https://github.com/terrestris/shogun-util/pull/63) introduced parameter for controlling the `TRANSPARENT` mode of a layer is now expected in here.
@terrestris/devs  please review
> Move transparent param to requestParam map

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
This PR allows custom request params for layer (e.g. `TRANSPARENT`, `FORMAT`, etc..)
> Allows custom request params

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
Bearer token header can now be set or unset with the layer config. 
By default it is always sent
> Bearer Token Header to be optional

- src/parser/SHOGunApplicationUtil.ts
This is might be useful if the token should be used/ignored in other components as well.
> Set useBearerToken as property of the layer

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
Be more specific while parsing of WMTS layers: 
* Optionally provide `matrixSet` parameter, which is required if there is more than one matrix set defined in the layer capabilities. 
* Manually compute matrix sizes
* In most cases the matrix dimensions are computed based `Math.pow(2, x)`  formula, where x points to the current zoom level
* An example for customized sizes: (e.g. [WMTS TopPlusOpen](https://sg.geodatenzentrum.de/wmts_topplus_open/1.0.0/WMTSCapabilities.xml?SERVICE=WMTS&REQUEST=GetCapabilities&VERSION=1.3.0) (MatrixSet `EU_EPSG_25832_TOPPLUS`)
Additionally set `matrixSizes` propetry on WMTS source to make it accessible for[ mapfish-print-manager](https://github.com/terrestris/mapfish-print-manager/blob/master/src/serializer/MapFishPrintV3WMTSSerializer.js#L67) and ensure, …
> Provide matrixSet name and compute matrix sizes

- package-lock.json
- package.json
- src/parser/SHOGunApplicationUtil.ts
* Bumps ol-util to v7.3.0
* Fixes initialization of the default proj4 definitions
Replaces https://github.com/terrestris/shogun-util/pull/97
> Bump ol-util to v7.3.0

- src/model/Application.ts
- src/parser/SHOGunApplicationUtil.ts
This adds support for application specific layer configurations, e.g. to make a layer hoverable/queryable in a specific application even if it is disabled by default.
Requires [!569](https://github.com/terrestris/shogun/pull/569).
> Apply application specific layer configs

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
- Add `opacity` property to layer parser
- Parse title and set it to layer name, needed to display the correct `title` within layertree
@terrestris/devs
> Add opacity to layer parser

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.spec.ts
- src/parser/SHOGunApplicationUtil.ts
Allows to save download related configuration in layer.clientConfig, e.g.:
```json
{
"hoverable": false,
"downloadConfig": [
{
"downloadUrl": "https://localhost/geoserver/SHOGUN/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SHOGUN%3APEGEL&maxFeatures=50&outputFormat=SHAPE-ZIP",
"formatName": "Shapefile"
},
{
"downloadUrl": "https://localhost/geoserver/SHOGUN/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SHOGUN%3APEGEL&maxFeatures=50&outputFormat=application%2Fjson",
"formatName": "GeoJSON"
}
]
}
``` 
@terrestris/devs Please review
> feat: add downloadConfig to layer

- src/parser/SHOGunApplicationUtil.ts
According to MDN object URLs created by `URL.createObjectUrl` must be revoked if used no longer.
> fix: revoke object urls when reloading tiles

- src/parser/SHOGunApplicationUtil.ts
Reverts parts of https://github.com/terrestris/shogun-util/pull/220.
With `no-cors` mode the auth bearer token will be ignored.
> fix: remove no-cors mode, otherwise authentication token won't be sent

- src/parser/SHOGunApplicationUtil.ts
Sets the `legendUrl` property on a WMTS layer if its provided in the capabilities document.
> Set legendUrl for WMTS layers

- src/parser/SHOGunApplicationUtil.ts
This MR fixes https://github.com/terrestris/shogun-util/pull/224#pullrequestreview-1211783974 and sets the `legendUrl` at the source. In a previous version a manually configured (in shogun-admin) `legendUrl` wasn't considered when the value was set at the layer. In the following step, the values are bounded to the layer by [`setLayerProperties`](https://github.com/terrestris/shogun-util/blob/83312339f65a5fe0b1d78e2afe49a6c905beb662/src/parser/SHOGunApplicationUtil.ts#L550), including the `legendUrl` stored at `sourceConfig`.
> Sets legend url on source for wmts

- package-lock.json
- package.json
- src/service/OpenAPIService/index.ts
- src/service/SHOGunAPIClient.ts
This adds support for requesting the OpenAPI spec in version 2 or 3.
Required due to [PR 595](https://github.com/terrestris/shogun/pull/595).
> OpenAPI v3 support

- src/model/Application.ts
- src/parser/SHOGunApplicationUtil.ts
Register additional CRS definitions on GIS client, if configured.
See also https://github.com/terrestris/shogun/pull/670
> feat: register possibly configured additional crs definitions on client

- src/model/Application.ts
See title, possible use case: An application shall always have a default language that is not the browser detected language.
Validation: iso language codes are accepted (`de`, `pl` etc.). Might be added ?
@terrestris/devs
> feat: add defaultLangauge type to clientconfig

- src/parser/SHOGunApplicationUtil.ts
Removes the overhead of object URLs in case no authentication is configured.
> fix: only use tile load function if necessary

- src/model/enum/EditFormComponentType.ts
This PR adds two missing `EditFormComponentType`s: `DISPLAY` and `SELECT`
> Fixes edit form component types

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
- adds searchConfig types
- set searchConfig to OL layers when parsing layers
@terrestris/devs Please review
> feat: add searchConfig to layer

- package-lock.json
- package.json
- src/parser/SHOGunApplicationUtil.ts
Bump ol-util to v11.0.0 and fix detection of WMSTime layer dimensions again:
- Adapt to sightly changed Capabilities document structure
- Fix detection of dimensions for layers requested via GetCapabilities v1.1.0 or v1.1.1
> Fix capabilities parser for WMSTime

- src/parser/SHOGunApplicationUtil.ts
- src/service/AppInfoService/index.ts
- src/service/ApplicationService/index.spec.ts
- src/service/ApplicationService/index.ts
- src/service/AuthService/index.ts
- src/service/CacheService/index.ts
- src/service/FileService/index.spec.ts
- src/service/GenericEntityService/index.spec.ts
- src/service/GenericEntityService/index.ts
- src/service/GenericFileService/index.ts
- src/service/GenericService/index.ts
- src/service/GraphQLService/index.ts
- src/service/GroupService/index.spec.ts
- src/service/GroupService/index.ts
- src/service/ImageFileService/index.spec.ts
- src/service/ImageFileService/index.ts
- src/service/LayerService/index.spec.ts
- src/service/LayerService/index.ts
- src/service/OpenAPIService/index.ts
- src/service/PermissionService/index.ts
- src/service/SHOGunAPIClient.ts
- src/service/UserService/index.spec.ts
- src/service/UserService/index.ts
This PR (BREAKING CHANGE) introduces an abstract base service `GenericService` holding `basePath` and `keycloak` instance for all subclasses.
Beside, the datatype of `GraphQLResponse` (field `data`) has been changed from `array` to a single one (also a breaking change)
> Introduce GenericService as abstract base service 

- src/model/Page.ts
- src/service/GenericEntityService/index.spec.ts
- src/service/GenericEntityService/index.ts
- src/service/GenericFileService/index.ts
- src/service/GenericService/index.ts
- src/service/SHOGunAPIClient.spec.ts
This enables support for paging in the `findAll()` service methods and thus enables to make use of [!606](https://github.com/terrestris/shogun/pull/606).
**BREAKING CHANGES:** 
- The signature of the `findAll()` methods changes from `findAll((fetchOpts?: RequestInit)): T[]` to `findAll(pageOpts?: PageOpts, fetchOpts?: RequestInit): Page<T>`
> Support paging in `findAll` service methods

- src/model/enum/LayerType.ts
- src/parser/SHOGunApplicationUtil.ts
**BREAKING CHANGE:** This renames the public enum from `WMSTime` to `WMSTIME` (which wasn't available in SHOGun before anyway).
Requires [!715](https://github.com/terrestris/shogun/pull/715).
> Set correct layer type name for WMSTIME

- src/parser/SHOGunApplicationUtil.ts
Even if typed as required, `sourceConfig` might be empty if returned otherwise from the server.
> Add non-null assertion operator

- src/parser/SHOGunApplicationUtil.spec.ts
- src/parser/SHOGunApplicationUtil.ts
This adds basic support for parsing [XYZ](https://openlayers.org/en/latest/apidoc/module-ol_source_XYZ-XYZ.html) layers.
> Add support for parsing XYZ layers

- src/model/Application.ts
- src/model/Layer.ts
- src/model/enum/EditFormComponentType.ts
This adds the `REFERENCE_TABLE` type (see [PR 710](https://github.com/terrestris/shogun/pull/710)).
> feat: include REFERENCE_TABLE type

- .github/workflows/on-push-main.yml
Run the release before updating the gh-pages branch. Otherwise the version number for the docs is outdated.
> Run release before updating gh-pages

- src/parser/SHOGunApplicationUtil.spec.ts
- src/parser/SHOGunApplicationUtil.ts
This refactors the `parseLayerTree` function by introducing a new function `parseLayerTreeNodes` that can has the same functionality, but without calling shogun, instead it gets the layers array passed in.
This also contains a small fix where resolutions was initialized with an empty array which was causing the map to have no available resolutions at all. No it remains undefined and the default resolutions of OpenLayers are used.
> Refactor parse layer tree

- package-lock.json
- package.json
- src/model/enum/LayerType.ts
- src/parser/SHOGunApplicationUtil.ts
- tsconfig.json
- watchBuild.js
This PR is based on the work of @dnlkoch in https://github.com/terrestris/shogun-util/pull/422 adding `mapbox-gl` layers for the ol7 maintenance branch.
In addition, the `mapbox` version was bumped to `10.7.0` (matching the one of `ol`) and the determination of the layer title was removed.
Please review.
> Branch `ol7`: basic support for mapboxstyle layers

- src/service/GenericEntityService/index.spec.ts
- src/service/GenericEntityService/index.ts
This adds the needed methods to the `GenericEntityService`.
It relies on https://github.com/terrestris/shogun/pull/850.
Closes #657
> Add methods for `PublicInstancePermission`

- src/model/Application.ts
This enables easy extension of the Application type like this:
```typescript
import Application, {
DefaultApplicationClientConfig,
DefaultApplicationLayerConfig,
DefaultApplicationToolConfig,
DefaultLayerTree
} from "@terrestris/shogun-util/dist/model/Application";
export type CustomApplicationClientConfig = DefaultApplicationClientConfig & {
listOrder: number;
backgroundLayers: number[];
};
export type CustomToolConfig = DefaultApplicationToolConfig & {
wmsLayerId: number;
wfsLayerId: number;
}
export type CustomApplication = Application<
CustomApplicationClientConfig,
DefaultLayerTree,
DefaultApplicationLayerConfig,
CustomToolConfig
>;
```
and use it via the `SHOGunAPIClient`:
```typescript
const application = client.application<CustomApplication>().findOne(234);
```
> feat: add generic parameters to application to make it easier to extend

- src/parser/SHOGunApplicationUtil.ts
The checked attribute should be ignored for groups. The attribute comes from the [layerTree](https://github.com/terrestris/shogun/blob/main/shogun-lib/src/main/java/de/terrestris/shogun/lib/model/jsonb/application/DefaultLayerTree.java) jsonb property of the Layer Model.
The checked state in the tree for a layer group is always dependent on the visibility of the children. If all children are visible the group is checked, if only some children are visible the group is partly checked and if none are visible the group is not checked.
The group visibility is never changed in the react-geo LayerTree, and it would be tricky to do so. It is better to ignore this value for groups and always keep them visible. If you want to check a complete group, just check all children.
Here is an example with …
> fix: ignore checked attribute for groups

- src/security/getBearerTokenHeader.ts
- src/security/getCsrfTokenHeader.ts
This changes the return types of the header functions so they can be used in a fetch without any type casts:
Also it switches `undefined` from the return type to an empty object so you can easily do something like this:
```typescript
const headers: HeadersInit = {
...getBearerTokenHeader(),
'other-header': 'value'
}
```
> fix: change return types of header functions

- src/model/Layer.ts
- src/parser/SHOGunApplicationUtil.ts
This PR introduces generics for sub types of `LayerClientConfig` and `LayerSourceConfig` that can be passed to layer instances. Herewith, layer classes having custom layer client configs (for example) can be used with the `SHOGunAPIClient`.
```
export default class ProjectLayer extends Layer<ProjectLayerClientConfig, DefaultLayerSourceConfig> {
constructor(layerArgs: LayerArgs<ProjectLayerClientConfig, DefaultLayerSourceConfig>) {
super(layerArgs);
}
}
```
> feat(layer): use generics for source and client config

- src/parser/SHOGunApplicationUtil.ts
- src/service/GraphQLService/index.ts
This prints the graphql error message as formatted JSON instead of `Object object`.
@terrestris/devs Please review
> Improve graphql error handling

- src/model/Application.ts
- src/parser/SHOGunApplicationUtil.spec.ts
- src/parser/SHOGunApplicationUtil.ts
This adds the `parseMapInteractions` method. It receives an applicationConfig and returns an array of openlayers Interactions. If no `mapInteractions` key is found in the `clientConfig` the default interactions will be used. If the array is empty the map will have no interactions and will have a static extent.
Test included :microscope:
> Adds method to parse map interactions

- jest.setup.js
- src/service/AuthService/index.spec.ts
- src/service/CacheService/index.spec.ts
- src/service/GenericEntityService/index.spec.ts
- src/service/GenericFileService/index.spec.ts
- src/service/ImageFileService/index.ts
- src/service/PermissionService/index.spec.ts
See title.
In addition, `ImageFileService` (`findOneThumbnail`) has been fixed. In particular, no CRSF has to be added to headers but an auth token using  `getBearerTokenHeader`.
> fix: mock CSRF meta elements in tests

- jest.config.js
- package-lock.json
- package.json
- src/model/enum/LayerType.ts
- src/parser/SHOGunApplicationUtil.ts
- tsconfig.json
This PR is based on the work of @dnlkoch in https://github.com/terrestris/shogun-util/pull/422 and the feature  added for `ol7` maintenance branch https://github.com/terrestris/shogun-util/pull/658
> feat: adds basic support for vector tiles / mapbox-style layers

- src/parser/SHOGunApplicationUtil.ts
The code will skip erroneous layers when parsing their config, but continue with others in such cases.
> fix: lenient layer parsing

- src/model/Layer.ts
This PR allows the configuration of a `resultDrawerConfig` within the `searchConfig` on a layer.
It is needed for https://github.com/terrestris/shogun-gis-client/pull/1943.
> Introduces searchFeatureConfig for layer config

- src/model/enum/LayerType.ts
- src/parser/SHOGunApplicationUtil.ts
This adds `OGC_FEATURES` as a layer type. Here is an example:
```json
{
"type": "OGC_FEATURES",
"sourceConfig": {
"url": "/pg_featureserv/collections/public.ifm_eq/items.json"
},
"id": 7
}
```
> feat: add OGC_FEATURES layer type
